version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
