"""Initial migration

Revision ID: c593d8777303
Revises: 
Create Date: 2025-03-28 00:27:10.396945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c593d8777303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('more_data', sa.Text(), nullable=True),
    sa.Column('categorized_sections', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('django_celery_beat_crontabschedule')
    with op.batch_alter_table('django_celery_beat_periodictask', schema=None) as batch_op:
        batch_op.drop_index('django_celery_beat_periodictask_clocked_id_47a69f82')
        batch_op.drop_index('django_celery_beat_periodictask_crontab_id_d3cba168')
        batch_op.drop_index('django_celery_beat_periodictask_interval_id_a8ca27da')
        batch_op.drop_index('django_celery_beat_periodictask_name_265a36b7_like')
        batch_op.drop_index('django_celery_beat_periodictask_solar_id_a87ce72c')

    op.drop_table('django_celery_beat_periodictask')
    op.drop_table('django_celery_beat_periodictasks')
    with op.batch_alter_table('story_storyitem', schema=None) as batch_op:
        batch_op.drop_index('story_storyitem_created_by_id_0888593b')

    op.drop_table('story_storyitem')
    op.drop_table('django_celery_beat_solarschedule')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_group_permissions_group_id_b120cbf9')
        batch_op.drop_index('auth_group_permissions_permission_id_84c5c92e')

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_index('auth_user_username_6821ab7c_like')

    op.drop_table('auth_user')
    op.drop_table('authentication_profile')
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_index('django_admin_log_content_type_id_c4bce8eb')
        batch_op.drop_index('django_admin_log_user_id_c564eba6')

    op.drop_table('django_admin_log')
    with op.batch_alter_table('story_comment', schema=None) as batch_op:
        batch_op.drop_index('story_comment_created_by_id_aa16b68e')
        batch_op.drop_index('story_comment_story_id_6f1fb245')

    op.drop_table('story_comment')
    op.drop_table('django_migrations')
    op.drop_table('django_celery_beat_intervalschedule')
    op.drop_table('django_content_type')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index('auth_group_name_a6ea08ec_like')

    op.drop_table('auth_group')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index('django_session_expire_date_a5c62663')
        batch_op.drop_index('django_session_session_key_c0390e0f_like')

    op.drop_table('django_session')
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.drop_index('auth_user_groups_group_id_97559544')
        batch_op.drop_index('auth_user_groups_user_id_6a12ed8b')

    op.drop_table('auth_user_groups')
    op.drop_table('django_celery_beat_clockedschedule')
    with op.batch_alter_table('story_vote', schema=None) as batch_op:
        batch_op.drop_index('story_vote_created_by_id_1bfd6880')
        batch_op.drop_index('story_vote_story_id_ab0147d0')

    op.drop_table('story_vote')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index('auth_permission_content_type_id_2f476e4b')

    op.drop_table('auth_permission')
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c')
        batch_op.drop_index('auth_user_user_permissions_user_id_a95ead1b')

    op.drop_table('auth_user_user_permissions')
    op.drop_table('staff_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_task',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('date_published', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.VARCHAR(length=200)), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='staff_task_pkey')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_user_user_permissions_user_id_a95ead1b', ['user_id'], unique=False)
        batch_op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', ['permission_id'], unique=False)

    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index('auth_permission_content_type_id_2f476e4b', ['content_type_id'], unique=False)

    op.create_table('story_vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='story_vote_created_by_id_1bfd6880_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story_storyitem.id'], name='story_vote_story_id_ab0147d0_fk_story_storyitem_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='story_vote_pkey')
    )
    with op.batch_alter_table('story_vote', schema=None) as batch_op:
        batch_op.create_index('story_vote_story_id_ab0147d0', ['story_id'], unique=False)
        batch_op.create_index('story_vote_created_by_id_1bfd6880', ['created_by_id'], unique=False)

    op.create_table('django_celery_beat_clockedschedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('django_celery_beat_clockedschedule_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('clocked_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_celery_beat_clockedschedule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.create_index('auth_user_groups_user_id_6a12ed8b', ['user_id'], unique=False)
        batch_op.create_index('auth_user_groups_group_id_97559544', ['group_id'], unique=False)

    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index('django_session_session_key_c0390e0f_like', ['session_key'], unique=False)
        batch_op.create_index('django_session_expire_date_a5c62663', ['expire_date'], unique=False)

    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_group_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index('auth_group_name_a6ea08ec_like', ['name'], unique=False)

    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('django_content_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('django_celery_beat_intervalschedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('django_celery_beat_intervalschedule_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('every', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_celery_beat_intervalschedule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('story_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='story_comment_created_by_id_aa16b68e_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story_storyitem.id'], name='story_comment_story_id_6f1fb245_fk_story_storyitem_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='story_comment_pkey')
    )
    with op.batch_alter_table('story_comment', schema=None) as batch_op:
        batch_op.create_index('story_comment_story_id_6f1fb245', ['story_id'], unique=False)
        batch_op.create_index('story_comment_created_by_id_aa16b68e', ['created_by_id'], unique=False)

    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.create_index('django_admin_log_user_id_c564eba6', ['user_id'], unique=False)
        batch_op.create_index('django_admin_log_content_type_id_c4bce8eb', ['content_type_id'], unique=False)

    op.create_table('authentication_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.VARCHAR(length=200)), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='authentication_profile_user_id_d23cdeb4_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='authentication_profile_pkey'),
    sa.UniqueConstraint('user_id', name='authentication_profile_user_id_key')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.create_index('auth_user_username_6821ab7c_like', ['username'], unique=False)

    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_group_permissions_permission_id_84c5c92e', ['permission_id'], unique=False)
        batch_op.create_index('auth_group_permissions_group_id_b120cbf9', ['group_id'], unique=False)

    op.create_table('django_celery_beat_solarschedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('django_celery_beat_solarschedule_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('event', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_celery_beat_solarschedule_pkey'),
    sa.UniqueConstraint('event', 'latitude', 'longitude', name='django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('story_storyitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('by', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('number_of_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dead', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('kids', postgresql.ARRAY(sa.VARCHAR(length=225)), autoincrement=False, nullable=True),
    sa.Column('descendants', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='story_storyitem_created_by_id_0888593b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='story_storyitem_pkey')
    )
    with op.batch_alter_table('story_storyitem', schema=None) as batch_op:
        batch_op.create_index('story_storyitem_created_by_id_0888593b', ['created_by_id'], unique=False)

    op.create_table('django_celery_beat_periodictasks',
    sa.Column('ident', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ident', name='django_celery_beat_periodictasks_pkey')
    )
    op.create_table('django_celery_beat_periodictask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('args', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('routing_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('crontab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('headers', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clocked_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expire_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('expire_seconds >= 0', name='django_celery_beat_periodictask_expire_seconds_check'),
    sa.CheckConstraint('priority >= 0', name='django_celery_beat_periodictask_priority_check'),
    sa.CheckConstraint('total_run_count >= 0', name='django_celery_beat_periodictask_total_run_count_check'),
    sa.ForeignKeyConstraint(['clocked_id'], ['django_celery_beat_clockedschedule.id'], name='django_celery_beat_p_clocked_id_47a69f82_fk_django_ce', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['crontab_id'], ['django_celery_beat_crontabschedule.id'], name='django_celery_beat_p_crontab_id_d3cba168_fk_django_ce', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['interval_id'], ['django_celery_beat_intervalschedule.id'], name='django_celery_beat_p_interval_id_a8ca27da_fk_django_ce', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['solar_id'], ['django_celery_beat_solarschedule.id'], name='django_celery_beat_p_solar_id_a87ce72c_fk_django_ce', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_celery_beat_periodictask_pkey'),
    sa.UniqueConstraint('name', name='django_celery_beat_periodictask_name_key')
    )
    with op.batch_alter_table('django_celery_beat_periodictask', schema=None) as batch_op:
        batch_op.create_index('django_celery_beat_periodictask_solar_id_a87ce72c', ['solar_id'], unique=False)
        batch_op.create_index('django_celery_beat_periodictask_name_265a36b7_like', ['name'], unique=False)
        batch_op.create_index('django_celery_beat_periodictask_interval_id_a8ca27da', ['interval_id'], unique=False)
        batch_op.create_index('django_celery_beat_periodictask_crontab_id_d3cba168', ['crontab_id'], unique=False)
        batch_op.create_index('django_celery_beat_periodictask_clocked_id_47a69f82', ['clocked_id'], unique=False)

    op.create_table('django_celery_beat_crontabschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.VARCHAR(length=240), autoincrement=False, nullable=False),
    sa.Column('hour', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('day_of_month', sa.VARCHAR(length=124), autoincrement=False, nullable=False),
    sa.Column('month_of_year', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_celery_beat_crontabschedule_pkey')
    )
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
